
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: my.domain.com
    http:
      paths:
      - backend:
          serviceName: nginx-loadbalancer
          servicePort: 80
  
---

 
# apiVersion: networking.k8s.io/v1beta1
# kind: Ingress
# metadata:
#   namespace: kube-logging
#   name: nginx-ingress
#   annotations:
#     kubernetes.io/ingress.class: nginx
# spec:
#   rules:  
#   - host: kibana.domain.com
#     http:
#       paths:
#       - backend:
#         serviceName: kibana.domain.com
#         servicePort: 5601
