# FROM nginx:1.19.7-alpine
FROM richarvey/nginx-php-fpm:1.9.1

# COPY nginx/nginx.conf /etc/nginx/nginx.conf

# COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

COPY www /usr/share/nginx/html

EXPOSE 80