apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv3
  labels:
    type: local
spec:
  storageClassName: elk-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/elk3"