apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv2
  labels:
    type: local
spec:
  storageClassName: elk-storage
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "~/data/elk2"