apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv
  labels:
    type: local
spec:
  storageClassName: elk-storage
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"