apiVersion: v1
kind: Service
metadata:
  name: nginx-custom
  labels:
    app: nginx-custom
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: nginx-custom

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nginx-custom-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: nginx.domain.com
    http:
      paths:
      - backend:
          serviceName: nginx-custom
          servicePort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-custom
spec:
  selector:
    matchLabels:
      app: nginx-custom
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-custom
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx-custom
              topologyKey: "kubernetes.io/hostname"

      containers:
      - name: nginx-custom
        image: insidus341/nginx-test:1.0
        ports:
        - containerPort: 80
