- hosts: master
  become: yes
  become_user: james

  tasks:
    - name: Update nginx-custom deployment
      command: "kubectl set image deployment/nginx-custom nginx-custom=insidus341/nginx-test:{{JENKINS_BUILD_NUMBER}} --record"