apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-loadbalancer
  name: nginx-loadbalancer
spec:
  ports:
  - name: 80-80
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.10.200

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - nginx
              topologyKey: "kubernetes.io/hostname"

      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80