






# /etc/nginx/conf.d/default.conf

server {
    listen       80;
    server_name  localhost;

    log_format  custom_log  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';


    access_log  /var/log/nginx/access.log  custom_log;
    error_log  /var/log/nginx/error.log  custom_log;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}

