- hosts: master
  become: yes
  become_user: james

  tasks:
    - name: Ensure destination directory exists
      command: mkdir -p ~/manifests/elk-stack

    - name: Copy required manifests
      ansible.builtin.copy:
        src: ~/kubernetes/manifests/elk-stack
        dest: ~/manifests/

    - name: Add elk namespace
      command: kubectl apply -f ~/manifests/elk-stack/namespace.yml

    - name: Add elasticsearch service
      command: kubectl apply -f ~/manifests/elk-stack/elasticsearch-svc.yml

    - name: Ensure the storageclass is made
      command: kubectl apply -f ~/manifests/elk-stack/elasticsearch-storage.yml
    
    - name: Add elasticsearch StatefulSet
      command: kubectl apply -f ~/manifests/elk-stack/elasticsearch-statefulset.yml

    # - name: Create configmap for Logstash
    #   command: kubectl apply -f ~/manifests/elk-stack/logstash-configmap.yml

    # - name: Initilize logstash
    #   command: kubectl apply -f ~/manifests/elk-stack/logstash.yml

    - name: Start fluentd 
      command: kubectl apply -f ~/manifests/elk-stack/fluentd.yml

    - name: Start kibana
      command: kubectl apply -f ~/manifests/elk-stack/kibana.yml

    # - name: Start the filebeat daemon
    #   command: kubectl apply -f ~/manifests/elk-stack/filebeat-daemon.yml



    # - name: Add second Deployment to Kubernetes Cluster
    #   command: kubectl apply -f ~/manifests/nginx-hello-kubernetes/hello-kubernetes-second.yml  

    # - name: Add Ingress service
    #   command: kubectl apply -f ~/manifests/nginx-hello-kubernetes/hello-kubernetes-ingress.yml