- hosts: master
  become: yes
  become_user: james

  tasks:
    - name: Ensure destination directory exists
      command: mkdir -p ~/manifests/prometheus-stack

    - name: Copy required manifests
      ansible.builtin.copy:
        src: ~/kubernetes/manifests/prometheus-stack
        dest: ~/manifests/
    
    - name: Add prometheus namespace
      command: kubectl apply -f ~/manifests/prometheus-stack/namespace.yml
      
    - name: Add helm chart for Prometheus stack
      shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts --force-update
        helm repo update
    
    - name: Install Prometheus stack
      command: helm install prometheus prometheus-community/kube-prometheus-stack -n kube-monitoring

    - name: Create prometheus ingress
      command: kubectl apply -f ~/manifests/prometheus-stack/prometheus-ingress.yml

    - name: Start grafana
      command: kubectl apply -f ~/manifests/prometheus-stack/grafana-ingress.yml