- hosts: master
  become: yes
  become_user: james

  tasks:
    - name: Get cluster nodes
      command: kubectl get nodes
      register: node_status
    
    - name:
      ansible.builtin.debug:
        var: node_status['stdout_lines']

    - name: Get pods 
      command: kubectl get pods -o wide
      register: pod_status
    
    - name:
      ansible.builtin.debug:
        var: pod_status['stdout_lines']
      
      