- hosts: master
  become: yes
  become_user: james

  tasks:
    - name: Ensure destination directory exists
      command: mkdir -p ~/manifests/python-influxdb-ping

    - name: Copy required manifests
      ansible.builtin.copy:
        # src: ~/kubernetes/manifests/nginx-custom
        src: "~/kubernetes/manifests/python-influxdb-ping"
        dest: ~/manifests/

    - name: Run python-influxdb-ping daemonset
      command: kubectl apply -f ~/manifests/python-influxdb-ping/daemonset.yml
