- hosts: master
  become: yes
  become_user: james

  tasks:
    - name: Ensure destination directory exists
      command: mkdir -p ~/manifests/ingress

    - name: Copy required manifests
      ansible.builtin.copy:
        src: ~/kubernetes/manifests/ingress
        dest: ~/manifests/

    - name: Run Nginx deployment
      command: kubectl apply -f ~/manifests/ingress/master-ingress.yml